export const SPECIALIZATIONS = [
  "Alergolog",
  "Anestezjolog",
  "Chirurg ogólny",
  "Chirurg plastyczny",
  "Dermatolog",
  "Diabetolog",
  "Endokrynolog",
  "Gastrolog",
  "Ginekolog",
  "Hematolog",
  "Internista",
  "Kardiolog",
  "Laryngolog",
  "Medycyna pracy",
  "Nefrolog",
  "Neurochirurg",
  "Neurolog",
  "Okulista",
  "Onkolog",
  "Ortopeda",
  "Pediatra",
  "Psychiatra",
  "Pulmonolog",
  "Radiolog",
  "Reumatolog",
  "Urolog"
].sort();